services:
  database:
    image: postgres:14.23-trixie
    container_name: golfnvibes_db
    env_file:
      - ./Backend/.env
    ports:
      - "5432"
    volumes:
      - golfnvibes_db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./Backend/.env
    ports:
      - "8000"
    depends_on:
      - database
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000"
    depends_on:
      - backend
    restart: always

volumes:
  golfnvibes_db_data: